ipv6-proxy:
  image: tetrag/ipv6-proxy
  cap_add:
    - NET_ADMIN
  volumes:
   - /vmsssd/3proxy/3proxy.cfg:/root/3proxy/3proxy.cfg
   - /vmsssd/3proxy/ndppd.conf:/root/ndppd/ndppd.conf
   - /vmsssd/3proxy/init.sh:/init.sh
  ports:
   - 30000-31000:30000-31000
  tty: true

